### ISSUE TITLE
压测中出现 spawn gm ENFILE

### ISSUE THREAD

**Issue by vincenting** [vincenting/campto#1]
使用 ab 进行压测的时候，在连续请求验证码接口一段时间后出现如下错误：

```
events.js:141
throw er; // Unhandled 'error' event
^

Error: spawn gm ENFILE
at exports._errnoException (util.js:837:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at doNTCallback2 (node.js:429:9)
at process._tickCallback (node.js:343:17)
```

**Comment by vincenting** [comment]
最新测试进展在 ab 测试到成功 1117 次后，即在 1118 次请求中爆出如下错误：

```
 /Project/vincent/campto/node_modules/gm/lib/command.js:227
    proc.stdin.once('error', cb);
              ^

TypeError: Cannot read property 'once' of undefined
    at gm._spawn (/Project/vincent/campto/node_modules/gm/lib/command.js:227:15)
    at /Project/vincent/campto/node_modules/gm/lib/command.js:140:19
    at series (/Project/vincent/campto/node_modules/gm/node_modules/array-series/index.js:11:36)
    at gm._preprocess (/Project/vincent/campto/node_modules/gm/lib/command.js:177:5)
    at gm.stream (/Project/vincent/campto/node_modules/gm/lib/command.js:138:10)
    at gm.toBuffer (/Project/vincent/campto/node_modules/gm/lib/command.js:162:17)
    at null.<anonymous> (/Project/vincent/campto/lib/builder/index.js:53:16)
    at /Project/vincent/campto/lib/builder/index.js:43:18
    at /Project/vincent/campto/lib/builder/index.js:96:29
    at CaptchaBuilder.getBackgroundImage (/Project/vincent/campto/lib/builder/index.js:139:5)
```

此时 `ulimit -a` 结果如下：

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

**Comment by vincenting** [comment]
定位为使用 node-temp 未及时关闭返回的 fd。

**Comment by JonSchapiro** [comment]
Was this issue ever solved. I'm facing the same but I dont speak chinese :(

**Comment by vincenting** [comment]
Hi @jSchapiroAtTheMelt :

I finally figured out that my problem was a mistaken usage with [node-temp](https://github.com/bruce/node-temp). When use `require('temp').open`, it will always create a new  file descriptor and open a file for you.

So, you can try to confirm is there any unclosed file descriptor in your code. Fix that and try again. ( Hope it can help to solve your problem.
